### ISSUE TITLE
Standalone mode stopped working.

### ISSUE THREAD

**Issue by andwah** [StarcounterPrefabs/UserAdmin#41]
This app should work without launcher.

**Comment by warpech** [comment]
@diliger could you investigate this? Please compare with Products app.

**Comment by diliger** [comment]
probably the problem is in **SignIn** application, it doesn't work in Standalone mode, should it?

If i firstly sign in with **Launcher**, then stop Launcher **UserAdmin** works fine.
But if user is not signed in then **UserAdmin** redirects to **SignIn**: `/signin/signinuser?%2fuseradmin%2fadmin%2fusers` and blank page appears.

![image](https://cloud.githubusercontent.com/assets/15857369/21674301/1d68509e-d33e-11e6-838a-27e89ee893ee.png)

**Comment by warpech** [comment]
I think UserAdmin should *include* a partial that is mapped to SignIn, not redirect to it. This should fix the problem.

**Comment by warpech** [comment]
Clarification:

- When the user is not signed in, `CurrentPage` should include a special partial. You might call it "UnauthenticatedPage.html" and give it a [401 HTTP](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error) error code
- Map this partial with UriMapping to `/sc/mapping/userform`. Sign In app already has a mapping for this URL.

**Comment by diliger** [comment]
PR #53

**Comment by diliger** [comment]
can be closed now?

**Comment by warpech** [comment]
Done, closing
